BEGIN;

UPDATE specifications SET description='AMS-224EN-4530 merupakan JUKI Pattern Stitching Machine untuk menjahit pola pada material menengah hingga sangat berat.' WHERE id=954;
UPDATE specifications SET description='Mesin bertipe computer-controlled cycle sewing machine yang mengendalikan proses jahit pola secara terprogram.' WHERE id=955;
UPDATE specifications SET description='AMS-224EN-4530 dikonfigurasi untuk material medium-to-heavy weight hingga extra-heavy weight.' WHERE id=956;
UPDATE specifications SET description='Area jahit mesin adalah 450 × 300 mm, dengan rentang gerak X 450 mm dan Y 300 mm.' WHERE id=957;
UPDATE specifications SET description='Kecepatan jahit maksimum yang tercantum adalah 2.500 sti/min untuk stitch length 3 mm atau kurang.' WHERE id=958;
UPDATE specifications SET description='Feeding frame menggunakan intermittent feed dengan penggerak 2-shaft stepping motor untuk mengatur gerakan X-Y.' WHERE id=959;
UPDATE specifications SET description='Panjang jahitan dapat diatur dari 0,1 hingga 12,7 mm dengan resolusi minimum 0,05 mm.' WHERE id=960;
UPDATE specifications SET description='Needle bar stroke yang tercantum untuk AMS-224EN-4530 adalah 41,2 mm.' WHERE id=961;
UPDATE specifications SET description='Jarum standar yang tercantum adalah DP×17 untuk konfigurasi AMS-224EN.' WHERE id=962;
UPDATE specifications SET description='Feeding frame dapat diangkat hingga maksimum 30 mm melalui external/feeding frame lift.' WHERE id=963;
UPDATE specifications SET description='Intermediate presser memiliki stroke standar 4 mm dan dapat diatur pada rentang 0–10 mm.' WHERE id=964;
UPDATE specifications SET description='Lift intermediate presser yang tercantum adalah 20 mm.' WHERE id=965;
UPDATE specifications SET description='Posisi bawah intermediate presser adalah 0–3,5 mm sebagai standar dan dapat mencapai maksimum 0–7,0 mm.' WHERE id=966;
UPDATE specifications SET description='Ketinggian intermediate presser dapat dikontrol secara stepless melalui pemrograman dengan penggerak stepping motor.' WHERE id=967;
UPDATE specifications SET description='Sistem needle thread tension menggunakan active tension untuk mengontrol tegangan benang secara elektronik.' WHERE id=968;
UPDATE specifications SET description='Upper thread breakage detection merupakan perlengkapan standar untuk mendeteksi putusnya benang atas selama proses jahit.' WHERE id=969;
UPDATE specifications SET description='Thread clamp digerakkan oleh pulse motor dan berfungsi menjepit benang di bawah needle plate untuk membantu mencegah benang terlepas pada awal jahitan.' WHERE id=970;
UPDATE specifications SET description='Mesin menggunakan double-capacity full-rotary hook dengan kapasitas bobbin besar.' WHERE id=971;
UPDATE specifications SET description='Pattern memory mendukung hingga 999 patterns dengan maksimum 50.000 stitches untuk setiap pattern.' WHERE id=972;
UPDATE specifications SET description='External media memory mendukung hingga 999 patterns dengan maksimum 50.000 stitches untuk setiap pattern.' WHERE id=973;
UPDATE specifications SET description='Pola jahitan dapat diperbesar atau diperkecil secara independen pada sumbu X dan Y.' WHERE id=974;
UPDATE specifications SET description='Oli pelumas yang ditentukan adalah JUKI New Defrix Oil No.2.' WHERE id=975;
UPDATE specifications SET description='Kepala mesin menggunakan compact AC servomotor dengan sistem direct-drive sebagai penggerak.' WHERE id=976;
UPDATE specifications SET description='Kebutuhan listrik tersedia dalam konfigurasi single-phase 100 V atau three-phase 200–240 V sesuai konfigurasi mesin.' WHERE id=977;
UPDATE specifications SET description='Konsumsi daya nominal yang tercantum adalah 550 VA.' WHERE id=978;
UPDATE specifications SET description='Kebutuhan compressed air adalah 0,5–0,55 MPa, dengan tekanan maksimum 0,55 MPa dan konsumsi 1,8 dm³/min tanpa AW-3.' WHERE id=979;
UPDATE specifications SET description='Bobbin thread counter menyediakan penghitungan UP/DOWN pada rentang 0–9.999.' WHERE id=980;
UPDATE specifications SET description='Sewing counter menyediakan penghitungan UP/DOWN pada rentang 0–9.999 untuk memantau jumlah jahitan atau produk.' WHERE id=981;
UPDATE specifications SET description='Memory backup secara otomatis menyimpan pola yang sedang digunakan ketika terjadi pemadaman listrik.' WHERE id=982;
UPDATE specifications SET description='Fungsi 2nd origin setting tersedia sehingga posisi 2nd origin dapat ditentukan dengan jog keys dan disimpan dalam memory.' WHERE id=983;
UPDATE specifications SET description='Mesin menggunakan servo motor sebagai penggerak kepala mesin.' WHERE id=984;
UPDATE specifications SET description='Dimensi mesin adalah 1.703 × 1.370 × 1.200 mm (W × D × H), tidak termasuk thread stand.' WHERE id=985;
UPDATE specifications SET description='Gross mass AMS-224EN-4530 yang tercantum adalah 401 kg.' WHERE id=986;
UPDATE specifications SET description='Rentang suhu operasi yang tercantum adalah 5–35 °C.' WHERE id=987;
UPDATE specifications SET description='Kelembapan operasi yang diizinkan adalah 35–85 % RH tanpa kondensasi.' WHERE id=988;
UPDATE specifications SET description='Line voltage yang digunakan adalah rated voltage ±10% pada frekuensi jaringan 50/60 Hz.' WHERE id=989;

COMMIT;
