BEGIN;

UPDATE specifications SET description='AMS-224EN-6030 merupakan JUKI Pattern Stitching Machine untuk material medium-to-heavy weight hingga extra-heavy weight.' WHERE id=990;
UPDATE specifications SET description='Mesin bertipe computer-controlled cycle sewing machine yang mengendalikan proses jahit pola secara terprogram.' WHERE id=991;
UPDATE specifications SET description='AMS-224EN-6030 tersedia dalam konfigurasi HS6030 dan GB6030 untuk material medium-to-heavy hingga extra-heavy weight.' WHERE id=992;
UPDATE specifications SET description='Area jahit mesin adalah 600 × 300 mm, dengan rentang gerak X 600 mm dan Y 300 mm.' WHERE id=993;
UPDATE specifications SET description='Kecepatan jahit maksimum yang tercantum adalah 2.500 sti/min untuk stitch pitch 3 mm atau kurang.' WHERE id=994;
UPDATE specifications SET description='Feeding frame menggunakan intermittent feed dengan penggerak 2-shaft stepping motor untuk mengatur gerakan X-Y.' WHERE id=995;
UPDATE specifications SET description='Panjang jahitan dapat diatur dari 0,1 hingga 12,7 mm dengan resolusi minimum 0,05 mm.' WHERE id=996;
UPDATE specifications SET description='Needle bar stroke yang tercantum untuk AMS-224EN-6030 adalah 41,2 mm.' WHERE id=997;
UPDATE specifications SET description='Jarum menggunakan DP×17. Untuk HS6030 tercantum ukuran #18, sedangkan GB6030 menggunakan ukuran #23.' WHERE id=998;
UPDATE specifications SET description='Ukuran benang bergantung pada konfigurasi: HS6030 menggunakan #50–#2, sedangkan GB6030 menggunakan #20–#2.' WHERE id=999;
UPDATE specifications SET description='Feeding frame dapat diangkat hingga maksimum 30 mm melalui external feeding frame lift.' WHERE id=1000;
UPDATE specifications SET description='Intermediate presser memiliki stroke standar 4 mm dan dapat diatur pada rentang 0–10 mm.' WHERE id=1001;
UPDATE specifications SET description='Lift intermediate presser yang tercantum adalah 20 mm.' WHERE id=1002;
UPDATE specifications SET description='Posisi bawah intermediate presser adalah 0–3,5 mm sebagai standar dan dapat mencapai maksimum 0–7,0 mm.' WHERE id=1003;
UPDATE specifications SET description='Ketinggian intermediate presser dapat dikontrol secara stepless melalui pemrograman dengan penggerak stepping motor.' WHERE id=1004;
UPDATE specifications SET description='Sistem needle thread tension menggunakan active tension dengan mekanisme pengaturan tegangan benang secara elektronik.' WHERE id=1005;
UPDATE specifications SET description='Upper thread breakage detection merupakan perlengkapan standar untuk mendeteksi putusnya benang atas.' WHERE id=1006;
UPDATE specifications SET description='Upper thread clamp digerakkan pulse motor dan menjepit benang di sisi bawah needle plate untuk membantu mencegah benang terlepas pada awal jahitan.' WHERE id=1007;
UPDATE specifications SET description='Thread trimming menggunakan pulse-motor high-speed thread trimming mechanism untuk melakukan pemotongan benang dengan cepat.' WHERE id=1008;
UPDATE specifications SET description='Mesin menggunakan double-capacity full-rotary hook dengan kapasitas bobbin besar.' WHERE id=1009;
UPDATE specifications SET description='Pattern memory memiliki kapasitas 500.000 stitches dan hingga 999 patterns, dengan maksimum 50.000 stitches untuk setiap pattern.' WHERE id=1010;
UPDATE specifications SET description='External media memory memiliki kapasitas hingga 50.000.000 stitches dan 999 patterns, dengan maksimum 50.000 stitches untuk setiap pattern.' WHERE id=1011;
UPDATE specifications SET description='Pola dapat diperbesar atau diperkecil pada rentang 1–400%, dengan pengaturan sumbu X dan Y secara independen dan langkah 0,1%.' WHERE id=1012;
UPDATE specifications SET description='Bobbin thread counter menyediakan penghitungan UP/DOWN pada rentang 0–9.999.' WHERE id=1013;
UPDATE specifications SET description='Sewing counter menyediakan penghitungan UP/DOWN pada rentang 0–9.999 untuk memantau jumlah jahitan atau produk.' WHERE id=1014;
UPDATE specifications SET description='Memory backup secara otomatis menyimpan pola yang sedang digunakan ketika listrik terputus.' WHERE id=1015;
UPDATE specifications SET description='Fungsi 2nd origin setting tersedia dan posisi 2nd origin dapat disimpan dalam memory.' WHERE id=1016;
UPDATE specifications SET description='Sistem pelumasan menggunakan grease untuk frame serta tank lubrication untuk hook dan hook driving shaft gearbox.' WHERE id=1017;
UPDATE specifications SET description='Oli pelumas yang ditentukan adalah JUKI New Defrix Oil No.2 dengan spesifikasi setara ISO VG32.' WHERE id=1018;
UPDATE specifications SET description='Kepala mesin menggunakan compact AC servomotor dengan sistem direct-drive.' WHERE id=1019;
UPDATE specifications SET description='Kebutuhan listrik yang tercantum adalah single-phase 100 V atau three-phase 200 V sesuai konfigurasi.' WHERE id=1020;
UPDATE specifications SET description='Konsumsi daya nominal yang tercantum adalah 550 VA.' WHERE id=1021;
UPDATE specifications SET description='Kebutuhan compressed air adalah 0,5–0,55 MPa, dengan tekanan maksimum 0,55 MPa dan konsumsi 1,8 dm³/min ANR.' WHERE id=1022;
UPDATE specifications SET description='Dimensi mesin adalah 1.923 × 1.370 × 1.200 mm (W × D × H), tidak termasuk thread stand.' WHERE id=1023;
UPDATE specifications SET description='Gross mass AMS-224EN-6030 yang tercantum adalah 410 kg.' WHERE id=1024;
UPDATE specifications SET description='Rentang suhu operasi yang tercantum adalah 5–35 °C.' WHERE id=1025;
UPDATE specifications SET description='Kelembapan operasi yang diizinkan adalah 35–85 % RH tanpa kondensasi.' WHERE id=1026;
UPDATE specifications SET description='Line voltage menggunakan rated voltage ±10% pada frekuensi jaringan 50/60 Hz.' WHERE id=1027;

COMMIT;
