UPDATE specifications SET description='JTK18F-1000AJ merupakan Large Area Fully Automatic Pattern Template Sewing Machine dari JUITA untuk proses jahit pola pada area kerja yang luas.' WHERE id=218;
UPDATE specifications SET description='Sistem kontrol menggunakan CNC system untuk mengendalikan gerakan dan proses jahit secara terprogram.' WHERE id=219;
UPDATE specifications SET description='Jenis jahitan yang digunakan adalah lockstitch, yaitu jahitan kunci yang dibentuk oleh interaksi benang atas dan benang bawah.' WHERE id=220;
UPDATE specifications SET description='Area jahit pada sumbu X mencapai 130 cm sebagai effective sewing range.' WHERE id=221;
UPDATE specifications SET description='Area jahit pada sumbu Y mencapai 100 cm sebagai effective sewing range.' WHERE id=222;
UPDATE specifications SET description='Kecepatan jahit berada pada rentang 200–3.500 rpm dan dapat berbeda menurut model, gauge, material, serta kondisi jahitan.' WHERE id=223;
UPDATE specifications SET description='Panjang jahitan dapat diatur dari 0,5 hingga 12,7 mm sesuai kebutuhan pola dan material.' WHERE id=224;
UPDATE specifications SET description='Sistem RFID digunakan untuk identifikasi template secara otomatis sebelum atau selama proses pengoperasian mesin.' WHERE id=225;
UPDATE specifications SET description='Kapasitas pola atau template disebut unlimited, dengan kapasitas yang dapat ditingkatkan dari batas 999 menjadi unlimited.' WHERE id=226;
UPDATE specifications SET description='Program dapat dimasukkan melalui PC menggunakan USB atau U-disk sebagai perangkat input.' WHERE id=227;
UPDATE specifications SET description='Sistem dapat mengenali format file CAD seperti DXF, PLT, AI, dan format lain yang kompatibel.' WHERE id=228;
UPDATE specifications SET description='Memori program menggunakan EPROM sebagai media penyimpanan program mesin.' WHERE id=229;
UPDATE specifications SET description='Mesin mendukung jarum DP×5 ukuran #7–#24 dan DP×17 ukuran #11–#24 sesuai kebutuhan proses jahit.' WHERE id=230;
UPDATE specifications SET description='Hook menggunakan imported twice large hook dengan ukuran sekitar dua kali lebih besar dibanding hook standar untuk mendukung kapasitas benang yang lebih besar.' WHERE id=231;
UPDATE specifications SET description='Sistem thread trimming menggunakan circular knife thread trimming untuk memotong benang secara otomatis.' WHERE id=232;
UPDATE specifications SET description='Mesin dilengkapi perangkat laser cutting untuk proses pemotongan material atau bagian pola sesuai konfigurasi mesin.' WHERE id=233;
UPDATE specifications SET description='Bottom thread detection tersedia untuk mendeteksi kondisi atau keberadaan benang bawah selama pengoperasian.' WHERE id=234;
UPDATE specifications SET description='Mesin menggunakan dua servo motor, masing-masing untuk menggerakkan upper shaft dan hook shaft secara independen.' WHERE id=235;
UPDATE specifications SET description='Panel operasi menggunakan smart touch operation panel dan mendukung transfer, pembacaan, serta penyimpanan data melalui U-disk.' WHERE id=236;
UPDATE specifications SET description='Sistem operasi mendukung delapan bahasa untuk memudahkan pengoperasian oleh pengguna dengan pilihan bahasa yang berbeda.' WHERE id=237;
UPDATE specifications SET description='Konektivitas Wi-Fi menyediakan kemampuan IoT yang dapat digunakan sebagai bagian dari konsep smart factory.' WHERE id=238;
UPDATE specifications SET description='Mesin menggunakan power supply 220 V sesuai spesifikasi kelistrikan yang tercantum.' WHERE id=239;
UPDATE specifications SET description='Berat bruto mesin tercatat sekitar 700 kg.' WHERE id=240;
UPDATE specifications SET description='Dimensi mesin adalah 220 × 132 × 138 cm (L × W × H). Data mencantumkan volume sekitar 4.000 CBM.' WHERE id=241;
