UPDATE specifications SET description='MB6003A merupakan IMB Shirt Buttonhole Indexer untuk proses pembuatan dan penempatan lubang kancing pada kemeja secara otomatis.' WHERE id=303;
UPDATE specifications SET description='Mesin menggunakan power supply 220–240 V, 1 phase, 50–60 Hz sesuai data katalog IMB.' WHERE id=304;
UPDATE specifications SET description='Daya listrik mesin tercatat sebesar 0.80 kW berdasarkan data katalog IMB.' WHERE id=305;
UPDATE specifications SET description='Kebutuhan tekanan udara kerja mesin adalah 5.5 bar berdasarkan data katalog IMB.' WHERE id=306;
UPDATE specifications SET description='Konsumsi udara mesin tercatat sebesar 42 L/min berdasarkan data katalog IMB.' WHERE id=307;
UPDATE specifications SET description='Kapasitas produksi mesin mencapai hingga 240 kemeja per jam berdasarkan data katalog IMB.' WHERE id=308;
UPDATE specifications SET description='Aplikasi utama mesin adalah shirt buttonhole indexing untuk membuat dan mengatur posisi lubang kancing pada kemeja.' WHERE id=309;
UPDATE specifications SET description='Kecepatan jahit maksimum mesin tercatat sebesar 4.200 spm berdasarkan data teknis IMB MB6003A.' WHERE id=1108;
UPDATE specifications SET description='Panjang lubang kancing yang dapat dibuat adalah hingga 25 mm.' WHERE id=1109;
UPDATE specifications SET description='Ukuran cutter yang didukung berada pada rentang 6,4–19,1 mm.' WHERE id=1110;
UPDATE specifications SET description='Tinggi presser foot yang dapat digunakan adalah hingga 14 mm.' WHERE id=1111;
UPDATE specifications SET description='Mesin menggunakan jarum tipe DP×5 sesuai data teknis IMB MB6003A.' WHERE id=1112;
UPDATE specifications SET description='Jarak antar buttonhole dapat diatur hingga maksimum 610 mm sesuai data teknis mesin.' WHERE id=1113;
UPDATE specifications SET description='Jarak buttonhole terhadap tepi placket berada pada rentang 7–21 mm.' WHERE id=1114;
UPDATE specifications SET description='Jarak feeding maksimum yang dapat dicapai adalah hingga 610 mm.' WHERE id=1115;
UPDATE specifications SET description='Jarak dari bagian atas hingga buttonhole pertama adalah maksimum 140 mm.' WHERE id=1116;
UPDATE specifications SET description='Lebar placket yang dapat diproses berada pada rentang 220–420 mm.' WHERE id=1117;
UPDATE specifications SET description='Panjang placket yang dapat diproses berada pada rentang 480–880 mm.' WHERE id=1118;
UPDATE specifications SET description='Dimensi mesin adalah 2300 × 1100 × 1500 mm berdasarkan data teknis IMB MB6003A.' WHERE id=1119;
UPDATE specifications SET description='Berat mesin tercatat sebesar 353 kg berdasarkan data teknis IMB MB6003A.' WHERE id=1120;
UPDATE specifications SET description='Dimensi packing mesin adalah 2220 × 1070 × 1530 mm.' WHERE id=1121;
UPDATE specifications SET description='Berat packing mesin tercatat sebesar 483 kg.' WHERE id=1122;
UPDATE specifications SET description='Mesin menggunakan touch screen programming sebagai antarmuka untuk pengaturan dan pengendalian proses.' WHERE id=1123;
UPDATE specifications SET description='Laser positioning tersedia untuk membantu menentukan posisi material dan lubang kancing secara presisi.' WHERE id=1124;
UPDATE specifications SET description='Thread monitor tersedia untuk memantau kondisi benang selama proses jahit.' WHERE id=1125;
UPDATE specifications SET description='Sistem servo feeding menggunakan high precision servo motor untuk mengatur feeding material secara presisi.' WHERE id=1126;
